### ISSUE TITLE
SNSでシェア用の短い動画を作る（無料版）

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-filter-search#117]
SNSのタイムラインでパッと流れてきても伝わる＆いいじゃん！と思えるように簡潔なのが良いデス。
なので、YouTubeとかのレッスン動画とかと違い、操作に関しては雰囲気がわかれば良いので早送りしまくって短縮したいです。

* 1分以内に抑えたい
* 飛ばせる部分はカット
  （今回で言えば最初のプラグイン一覧の画面はなくてもOK）
* 早送りで伝わる部分は早送り操作で尺を短くする

感じでよろしくお願いいたします。

で、佐々木さんが作った 不動産サイトのデモサイトなど（別のジャンルで自分で作っても可）で作った方が閲覧者が利用シーンをイメージしやすいので良いと思います。

最初と最後の定形のステッカーとかは特にありません。
自分で新規に作ってもらってもOKデス。
PatternGeneratorの動画で使った素材など必要なものがある場合は @kaorock72 さんなどにお気軽にご連絡くださいー。

https://www.figma.com/file/ChMacAIaBTmbE3yNW1xVJS/vk-filter-search

**Comment by shimotmk** [comment]
@kurudrive 
こちらのタスク試しに動画を撮ってみたのですがこういう動画のことで大丈夫でしょうか？
https://user-images.githubusercontent.com/42362903/116659292-5803d200-a9cc-11eb-891d-ad16e16dc75f.mov

過去の動画のVektor,Inc.で投稿されているツイートのようにオープニングやエンディングのテンプレなどあれば編集します！
[https://twitter.com/search?q=from%3Avektor_inc%20%20filter%3Anative_video&src=typed_query&f=live
](https://twitter.com/search?q=from%3Avektor_inc%20%20filter%3Anative_video&src=typed_query&f=live
)

**Comment by kurudrive** [comment]
@shimotmk 

ありがとうございます！無指示ですみません！

ちょっと概要今からもう少し書きます。しばしお待ちを！

**Comment by shimotmk** [comment]
@kurudrive @kaorock72 
お疲れさまです！

ベースとなる動画を撮影したのですが、こちらで大丈夫そうでしょうか？
https://user-images.githubusercontent.com/42362903/117622505-a4f65e00-b1ad-11eb-9089-adc3e4737ce0.mov

他に付け足したほうがいい情報がありましたらつけます！

**Comment by kurudrive** [comment]
@shimotmk ありがとうございます。

1. 最初ブロックを挿入する時に多分一覧からだと探しにくいので、検索窓に VK Filter を入力する形でお願いしたいです。
2. 検索結果画面の見た目が悪いので、1カラム、カードレイアウトで...あ、好みが出ると思うので僕の方で調整しますね。

しばしお待ちを。

**Comment by kurudrive** [comment]
@shimotmk レイアウト修正しました。
https://demo.dev3.biz/vk-filter-search/?post_type=chintai&ekitoho=&kodawari=elevator&s=&vkfs_form_id=7a2dd53f-4cce-42c3-a510-888eca9e5d76

これで引き続きよろしくお願いいたします。
