### ISSUE TITLE
WPML と VK Filter Search の組み合わせで get_the_terms() の取得結果が複数回重複になってしまう

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-filter-search#119]

**Comment by drill-lancer** [comment]
下記をコメントアウトすれば症状は消えるのでこのあたりを見直す必要がありかと・・・
https://github.com/vektor-inc/vk-filter-search/blob/c94b45bd1619aa31468f32dd88e6ea5fed0fa595/inc/filter-search/package/class-vk-filter-search-block.php#L95-L100

**Comment by drill-lancer** [comment]
詳細は不明だが suppress_filters というものが悪さしてそうというのはわかりました。
https://wpdocs.osdn.jp/%E3%83%86%E3%83%B3%E3%83%97%E3%83%AC%E3%83%BC%E3%83%88%E3%82%BF%E3%82%B0/get_posts

試しに suppress_filters を false にすると発生しなくなりました。
競合案件なので石川さんがプルリクをマージしてから作業をします。

**Comment by drill-lancer** [comment]
無料版：
https://github.com/vektor-inc/vk-filter-search/pull/121
Pro版：
https://github.com/vektor-inc/vk-filter-search-pro/pull/59
