### ISSUE TITLE
【確認待ち】vk-filter-search / インサーターの位置

### ISSUE THREAD

**Issue by ChiakiKouno** [vektor-inc/vk-filter-search#133]
5.9 からインサーターの位置が変わったようです。
位置の変更は可能でしょうか？

## 5.8の時

![5 8-inserter](https://user-images.githubusercontent.com/43702482/152912473-5da09fe2-09cf-4b01-a316-e2b9eafc9274.png)

## 5.9 の現状
![5 9-inserter](https://user-images.githubusercontent.com/43702482/152912492-709678d7-c27f-4a12-96c4-3a2a26847144.png)

## 5.9 でリスト表示にすると、インサートボタンが隠れる
![スクリーンショット 2022-02-08 午前11 30 18](https://user-images.githubusercontent.com/43702482/152912894-706a6e8d-2ba6-47ea-8681-c01bf01e1529.png)

## こうなるといいな
![kibou](https://user-images.githubusercontent.com/43702482/152912519-4da9deb2-2eec-4622-8bbd-77ed9e3022ff.png)

**Comment by kurudrive** [comment]
@drill-lancer 今って無料版は完全に独立してるんだっけ？
修正はこっちのリポジトリに直接するのかな？
