### ISSUE TITLE
【確認待ち】vk-filter-search / リスト表示の反転アイコン

### ISSUE THREAD

**Issue by ChiakiKouno** [vektor-inc/vk-filter-search#134]
リスト表示で VK Filter Search ブロックを選択した際に、アイコンが白黒反転すると思います。
反転した時のアイコンのVKの「K」の表示がおかしくなっていたので、お手隙の時にご対応をお願いできたらと思いますmm

![listview-icon](https://user-images.githubusercontent.com/43702482/152927034-f173cc2b-1877-40e5-8bf7-df7e3a8f0bf9.png)

**Comment by kurudrive** [comment]
@goutetsuguma @sysbird キリの良いタイミングでこれよろしくお願いいたします。
Pro版の方もー。

**Comment by drill-lancer** [comment]
@goutetsuguma @kurudrive 
インナーブロックは反転させなくても OK ですか？

**Comment by goutetsuguma** [comment]
@kurudrive @drill-lancer 
>インナーブロックは反転させなくても OK ですか？

hover時の白黒反転の件ですが、、、他のVKブロックicon、ほとんど黒い部分が反転しないようでした、、、、
ひとまず、、、filter serch のインナーブロックだけなおしておこうかな。。。少々お待ちください

**Comment by goutetsuguma** [comment]
@drill-lancer アイコン修正しました！お手数ですが、さらっと確認＆マージお願いしますーmm
