### ISSUE TITLE
【1.3.5 以降確認待ち】FSE でのスタイル調整

### ISSUE THREAD

**Issue by ChiakiKouno** [vektor-inc/vk-filter-search#135]
WordPress 5.9
X29Version: 0.0.0
VK Blocks Pro  1.24.4
VK Filter Search 1.3.4

Front Page テンプレートに Post Content を設置して表示させました。
キーワードのフォーム欄が少し大きいなど調整が必要そうです。

<img width="1132" alt="スクリーンショット 2022-02-08 午後4 05 42" src="https://user-images.githubusercontent.com/43702482/152948249-5b52ae0f-4572-4033-88f9-66772fdbe371.png">

**Comment by goutetsuguma** [comment]
こちらにプルリク済ですmm
https://github.com/vektor-inc/vk-filter-search-pro/pull/144

**Comment by kurudrive** [comment]
@ChiakiKouno develop にはマージしました。develop をビルドして確認するか、1.3.5 より後のバージョンがリリースされてから確認よろしくお願いいたします。

**Comment by ChiakiKouno** [comment]
遅くなってしまいました！ Version 1.9.2 で美しく反映されておりました。ありがとうございました！
