### ISSUE TITLE
【石川確認待ち】FSE でのアーカイブページでの表示位置がおかしい

### ISSUE THREAD

**Issue by ChiakiKouno** [vektor-inc/vk-filter-search#136]
WordPress 5.9
X29Version: 0.0.0
VK Blocks Pro 1.24.4
VK Filter Search 1.3.4

Display on post type archive にチェックを入れて有効化し、
アーカイブページを表示させたところ、ページの一番はじめに、スタイルが切れた状態で表示されました。

<img width="611" alt="スクリーンショット 2022-02-08 午後4 05 13" src="https://user-images.githubusercontent.com/43702482/152948886-7af64684-4bcb-4122-940b-4b1e2e581bdd.png">

**Comment by kurudrive** [comment]
@drill-lancer これちょっと対策検討よろしくお願いいたします。

クエリーブロックの中におそらくフックがあって、FSEのテーマの場合はそのフックに対して出力するみたいな感じでいければいいのかなと思いつつ、それが無理なら、検索結果ページ用に検索フォーム表示用のブロックを作る感じになるのかなと。

**Comment by drill-lancer** [comment]
フックなんてなかった・・・
https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/query/index.php
・・・なのでとりあえずブロックテーマでは該当オプションを無効化します。
（アーカイブテンプレート編集時に VK Filter Search ブロックを乗せればよいのでは？）

**Comment by drill-lancer** [comment]
とりあえず FSE で無効化はしていました。
https://github.com/vektor-inc/vk-filter-search-pro/pull/104

あと、Filter Search Pro をリリースすると自動的に無料版や海外版もリリースされる使用にしようと思っているので
Pro 版にコミットしています。

**Comment by kurudrive** [comment]
@drill-lancer 

> （アーカイブテンプレート編集時に VK Filter Search ブロックを乗せればよいのでは？）

どの検索フォームブロックから検索結果ページに辿り着いたかによって表示するフォームが変動するので、
検索結果ページに特定のフォームを予め乗せるのは良策ではありません。

フックがないという事は表示用のブロックを用意する形でよろしくお願いいたします。

**Comment by kurudrive** [comment]
@drill-lancer 

- [ ] FSEの場合は「チェックしても検索結果にフォーム表示されないじゃん」と思われないように「検索結果画面のテンプレートに検索フォーム表示用の***ブロックを配置する必要があります」などのメッセージを表示してください。

**Comment by drill-lancer** [comment]
多分これ対応済みなので Close
