### ISSUE TITLE
【相談】検索ボタンの文字が14pxで小さい気がする

### ISSUE THREAD

**Issue by goutetsuguma** [vektor-inc/vk-filter-search#140]
多分わたしが書いた気がするけど、なぜ14pxにしたのかは思い出せませんでした。

なんとなく、ボタンの文字が小さい気がするのですが、みなさんどう思いますか。
もし同じご意見がある場合は、この作業を実行しようと思いますので、是非書き込んでください。

そこまで気になったことがないという意見もありましたので、いったんこのまま置いておきます。

**Comment by kurudrive** [comment]
必要ならパターンとかで対応
