### ISSUE TITLE
Allowing search result of a custom post type into a page

### ISSUE THREAD

**Issue by Saoming** [vektor-inc/vk-filter-search#151]
## What problem does this address?

I have a layout here that I am trying to achieve, please take a look at the Figma layout below:
[Figma](https://www.figma.com/file/m3g4dfX6dmiFjdBTfbxjZW/Improvement-of-VK-Search-Result?node-id=0%3A1&t=1eVV5H30GjFd02Ze-1
)

I find VK Filter is suitable for what I am trying to work on since the data that I have are stored in a custom post type. data inside the custom post type is stored in the ACF field and Custom Taxonomy. 

However, It is currently impossible to show the results on a page / make a change to the existing query loop block/custom block on a page.

## What is your proposed solution?

Potential Solutions 1:
Create a setting where it can control the getEditedPostAttribute on any custom block. *not sure if this is possible

Potential Solutions 2:
Create a setting where it can affect the query loop block

I am not really sure how this can work out but so far this is what I've found that or so on. Maybe this is a good start to think about solutions and what the product can be improved. 

Thank you, guys, for responding to me on twitter! I appreciate

**Comment by kurudrive** [comment]
@Saoming Thank you for your post!
however, I have a lot of work to do now, so please wait for a while until I reply 🙏

**Comment by Saoming** [comment]
Hi @kurudrive 

Thank you for responding to me. All good! I am also going to do my due diligence to learn more about the plugins and Gutenberg ecosystem.

**Comment by kurudrive** [comment]
Hi @Saoming sorry about late reply :)

If you think normally on the premise of the classic theme,
by the search.php, I thought it would be possible to switch the display elements by conditionally branching with the post type included in the query, even with the current specifications.

for example
1. Create one page like Figma layout for initial search
2. In the search.php of the search results, if it is from Filter Search (identified by query information or URL parameters), it is a format that displays a list of Figma layouts with conditional branching.

But as a premise
are you considering create by classic theme? or considering block theme?
and actually I don't glasp of your skill then, do you have skill of developing WordPress website by classic style ( use php )
or regardless of it, are you considering about premise of create by block theme?

**Comment by Saoming** [comment]
Hi @kurudrive 

Thank you for responding to me. let me answer your response below

> are you considering creating by classic theme? or considering a block theme?
and actually, I don't grasp your skill then, do you have the skill of developing a WordPress website in classic style ( use PHP )
or regardless of it, are you considering about premise of creating by block theme?

Yes. I have skills to develop WordPress websites in a classic style (PHP).
I am currently following this method here from 10up [WP Scaffold](https://github.com/10up/wp-scaffold). 

Currently, the way that I develop would be universal since I use both classic and block at the same time. But I am in the process to create fully functional block themes.

> If you think normally on the premise of the classic theme,
by the search.php, I thought it would be possible to switch the display elements by conditionally branching with the post type included in the query, even with the current specifications.

Ah, I was confused before with searchpage.php and search.php.

**Comment by kurudrive** [comment]
@Saoming 

If you considering on block theme, may be helpful below.

All in One WP migration data ( Deleted on 2023.3.20  )
https://drive.google.com/file/d/1oO8HIHDlhZ8NX1NmjtGe2OY-PmZa9jl6/view?usp=share_link
user : admin
pass : admin

but, this site's search reslut page premise only VK Filter Search that, If you want to have 2 Result Page ( Filter Search Result and Normal keyword search ) I expect you have to develop something original block or Control by CSS.
