### ISSUE TITLE
一度全ページの検索結果が表示 ➡︎ 瞬時にリダイレクトして正しい結果が表示される

### ISSUE THREAD

**Issue by ChiakiKouno** [vektor-inc/vk-filter-search#152]
Bissyさんより[Slackにてご報告](https://vektor-vws.slack.com/archives/CJD95D5LZ/p1682997578361279)いただきました（消えてしまうのでこちらに転記いたします）

一度全ページの検索結果が表示 ➡︎ 瞬時にリダイレクトして正しい結果が表示される
のですが、これは不具合でしょうか？ 仕様でしょうか？
レイアウトが一度崩れるので気になります。
投稿を検索しているのに、固定ページが一瞬表示されてしまう感じです。
　
よろしくお願いします:おじぎ_女性:
環境:

- VK Filter Search 最新版（1.14.3）
- Lightningテーマ最新版（15.8.6）
- WordPress最新版（6.2）
- PHP 8.0.25
- webサーバー Apache

　
試したこと:

- テーマの切り替え。TwentyTwentyThreeでも再現した。
- TreeShaking などをオフにしても再現した。
- 設置場所を、固定ページ、サイドバーに置いても再現した。
- 検索の条件を未指定のまま検索ボタン押下でも再現した。

**Comment by bissy** [comment]
こちら確認よろしくお願いします🙇‍♀️

**Comment by drill-lancer** [comment]
@bissy 
リダイレクト処理を Javascript の vk-filter-search-redirect.min.js で処理しているので仕様です。
JS が読み込まれた瞬間にリダイレクトが発動する仕様です。

ただ、通常だと上記 Javascript  はヘッダーで読み込んでいるので影響は皆無に等しいですが
もし、フッターで読み込まれている場合リダイレクトの発動が遅れるのでそういった現象が起こりえます。

一度上記の Javascript がどこで読み込まれているかソースコードを確認してみてください。
また、フッターで読み込まれている場合は関連するプラグイン・自作コード等を見直してみてください。

**Comment by bissy** [comment]
@drill-lancer 
ありがとうございます！
高速化をOFFにするのは残念ですが、OFFにしたらいい感じに動作するようになりました！
ありがとうございました🙇‍♀️

**Comment by drill-lancer** [comment]
解決した＆仕様なので Close

**Comment by waviaei** [comment]
ExUnit のリポジトリが見当たらないのでこちらに記します。ExUnit の JSフッター読み込みの仕様から、`vk-filter-search-redirect.min.js ` は除外する処理を追加した方が良いと思います。
