### ISSUE TITLE
特定の投稿タイプアーカイブで表示する機能が欲しい

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-filter-search#53]
親の検索ボックスに以下を追加。
検索結果ページのように上部に表示されるように。

---

■ アーカイブページでの表示
投稿タイプアーカイブページの投稿リストの上に表示する事ができます。
表示する場合は、該当の投稿タイプにチェックを入れてください。

[ ] 投稿
[ ] お知らせ
[ ] （そのほかpublicになっている固定ページ以外の投稿タイプ）

---

検索結果ページに表示するのと同じく option に保存する

```
array(
'display_on_result' = > ごにょごにょ,
'display_on_post_type_archive' => array(
        ['form_block_id'] => array(
            'post_type_archive' => arrray( 'post',event ),
            'form_post_id' => xxx,
            'form_content' => '',
        ),
    )
)
```

■ 編集ショートカット
ブロックログインしてる時検索ボックスの下に、"この検索ブロックを編集" を表示して、編集画面にリンクする。
admin_url().'/post.php?post='. form_block_id .'&action=edit

編集権限の判別は後日実装でもいいかなーとか思ったりする。

**Comment by drill-lancer** [comment]
https://github.com/vektor-inc/vk-filter-search/pull/60

**Comment by kurudrive** [comment]
@drill-lancer アーリがとうございましたー！！

_|＼○_ﾋｬｯ ε=＼＿○ﾉ ﾎｰｳ!!
