### ISSUE TITLE
検索ボックスだけが検索結果に表示されるように作り変える

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-filter-search#54]
現状の仕様だと

1. トップページに検索ボックスを追加して、その検索ボックスを検索結果にも表示する に指定
2. 検索を実行してみると、検索結果ページにトップページごと挿入しようとするので、トップページの構成によってはサイトごと落ちる

という状態で実用に耐えない状態なので

1. 検索ボックスで「検索結果に表示」にチェック
2. 検索結果画面でその検索ボックスが表示される

を実現できるように構造変更する必要がある。

**Comment by drill-lancer** [comment]
フォームのみ取得することは可能です。
ただし、検索結果上でのフォームの値の反映は JavaSctipt で行う必要がありますが・・・
https://github.com/vektor-inc/vk-filter-search/pull/55/

**Comment by drill-lancer** [comment]
検索結果の画面でも値が反映されるようになりました。
https://github.com/vektor-inc/vk-filter-search/pull/55

**Comment by kurudrive** [comment]
ありがとうございました！
