### ISSUE TITLE
検索結果がなかった時の処理

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-filter-search#56]
## 概要

通常 loop の前のフックで検索結果を表示しているが、検索結果が 0 件の場合ループ自体が存在しなかったりするケースがある。
そのため、テーマ個別でループの前くらいの位置に用意してあるフックで表示する機能があれば良いのではないか？

## 実装案

[ ] 検索結果ページにおいて、検索結果が0件の時、特定のフックがある場合 にそのフックを使ってフォームを出力する機能を書くわけだが、アクションフックの名称はテーマによって異なるので、対象のフック名を config ファイルに配列で持たせる。
[ ] 他のテーマで使いやすいようにフック名の配列はフィルターで変更できるようにしておく。

**Comment by drill-lancer** [comment]
下記コミットで実装しておきました。
https://github.com/vektor-inc/vk-filter-search/pull/55/commits/1a3abda6ae4fb5d496bb0a6635c33c1efc68a36e

**Comment by kurudrive** [comment]
こちらもありがとうございました！
