### ISSUE TITLE
検索結果に表示されなくなってる...

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-filter-search#70]
https://www.vektor-inc.co.jp/service/wordpress-plugins/vk-filter-search/

**Comment by kurudrive** [comment]
あ、トップページからだと出る

https://www.vektor-inc.co.jp/

**Comment by drill-lancer** [comment]
現在は表示されるようになってます。

**Comment by kurudrive** [comment]
ホントだ。正常に動いてますね。なんだろ...。
確認ありがとうございます。
