### ISSUE TITLE
プルダウン内のカテゴリー並び順を変えたい（階層構造を維持したい）

### ISSUE THREAD

**Issue by mypacecreator** [vektor-inc/vk-filter-search#73]
カテゴリー（階層のあるタクソノミー）の検索ブロックを使用した際、select要素内のカテゴリーの並び順が親子関係を無視して並列に（ID順かな？）並んでいるので、階層が維持された状態で並べられないでしょうか...?
もしくは、任意に並べ替えることができないか...?

**Comment by kurudrive** [comment]
@mypacecreator ふぉー、なるほどー。
了解です。が、ちょっと別件優先事項があるので少しお時間いただきます ＞＜

**Comment by mypacecreator** [comment]
@kurudrive いえいえ、面倒なissue立ててしまってすみませんすみません💦（御社フォーラムと迷ってこっちに書きました）
あくまで今後の開発の参考程度にご検討ください！

**Comment by kurudrive** [comment]
@miminari おまたせしましたん。1.0.0で階層維持するようになりましたー！
